version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27020:27017    
    environment:
      MONGO_INITDB_ROOT_USERNAME: test-user
      MONGO_INITDB_ROOT_PASSWORD: test-password
      MONGO_INITDB_DATABASE: test-db
    volumes:
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: test-password

volumes:
  db-data:
